project:
  type: website
  output-dir: docs

website:
  title: "Nepal expeditions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: View data
        href: dashboard.qmd
      - text: About
        href: about.qmd


format:
  html:
    theme:
    - cosmo
    - custom.scss
